#!/bin/bash
# // TEXT COLOR
export RED='\033[0;31m'
export GREEN='\033[0;32m'
export YELLOW='\033[0;33m'
export BLUE='\033[0;34m'
export PURPLE='\033[0;35m'
export CYAN='\033[0;36m'
export LIGHT='\033[0;37m'
export NC='\033[0m'
## /// BG COLOR
export BGRED='\e[41m'
export BGGREEN='\e[42m'
export BGYELLOW='\e[43m'
export BGBLUE='\e[44m'
export BGPURPLE='\e[45m'
export BGCYAN='\e[46m'
export BGWHITE='\e[47m'

export INFO="${YELLOW}[INFO]${NC}"
export ERROR="${RED}[ERROR]${NC}"
export DEV="${GREEN}[DEVTEAM]${NC}"
export OK="${GREEN}[SUCCESS]${NC}"
THEME="$BLUE"
THEMEBG="$BGBLUE"
